/** Toolkit cards + paths. Each tool: src/features/<id>/ */
export const TOOL_REGISTRY = [
  { id: 'edit-pdf', path: '/tools/edit-pdf', title: 'Edit PDF', description: 'Change text, annotate, highlight, draw.', implemented: true, icon: 'FileEdit' },
  {
    id: 'ocr-pdf',
    path: '/tools/ocr-pdf',
    title: 'OCR PDF',
    description: 'Make scans searchable — needs your API (ocrmypdf + Tesseract on the server).',
    implemented: true,
    icon: 'ScanText',
  },
  {
    id: 'merge-pdf',
    path: '/tools/merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDFs into one file.',
    implemented: true,
    icon: 'GitMerge',
  },
  {
    id: 'split-pdf',
    path: '/tools/split-pdf',
    title: 'Split PDF',
    description: 'Split by page ranges or extract every page.',
    implemented: true,
    icon: 'Scissors',
  },
  {
    id: 'organize-pdf',
    path: '/tools/organize-pdf',
    title: 'Organize Pages',
    description: 'Reorder, rotate, or delete pages, then download.',
    implemented: true,
    icon: 'LayoutGrid',
  },
  {
    id: 'add-page-numbers',
    path: '/tools/add-page-numbers',
    title: 'Add page numbers',
    description: 'Stamp page numbers with placement, ranges, and formats — in your browser.',
    implemented: true,
    icon: 'Hash',
  },
  {
    id: 'compress-pdf',
    path: '/tools/compress-pdf',
    title: 'Compress PDF',
    description: 'Tries your API (qpdf / Ghostscript); falls back to in-browser pdf-lib when the API is missing.',
    implemented: true,
    icon: 'Minimize2',
  },
  { id: 'pdf-to-jpg', path: '/tools/pdf-to-jpg', title: 'PDF to JPG', description: 'Export pages as JPEG. ZIP or single files.', implemented: true, icon: 'ImageDown' },
  {
    id: 'pdf-to-png',
    path: '/tools/pdf-to-png',
    title: 'PDF to PNG',
    description: 'Export pages as lossless PNG in a ZIP — all in your browser.',
    implemented: true,
    icon: 'Image',
  },
  {
    id: 'pdf-to-text',
    path: '/tools/pdf-to-text',
    title: 'PDF to text',
    description: 'Download plain .txt from selectable text (not for raw scans).',
    implemented: true,
    icon: 'AlignLeft',
  },
  { id: 'jpg-to-pdf', path: '/tools/jpg-to-pdf', title: 'JPG to PDF', description: 'Combine images. Drag to reorder.', implemented: true, icon: 'Images' },
  {
    id: 'scan-to-pdf',
    path: '/tools/scan-to-pdf',
    title: 'Scan to PDF',
    description: 'Camera or photos: trim, enhance, multi-page PDF.',
    implemented: true,
    icon: 'ScanLine',
  },
  {
    id: 'sign-pdf',
    path: '/tools/sign-pdf',
    title: 'Sign PDF',
    description: 'Sign any page, duplicate or copy/paste placements, then download.',
    implemented: true,
    icon: 'PenLine',
  },
  {
    id: 'e-sign-pdf',
    path: '/tools/e-sign',
    title: 'E-Sign PDF',
    description: 'Electronically sign in your browser: draw or upload a signature, place on any page, download.',
    implemented: true,
    icon: 'Signature',
  },
  {
    id: 'fill-pdf',
    path: '/tools/fill-pdf',
    title: 'Fill PDF form',
    description: 'Fill AcroForm fields and download — processing stays in the browser.',
    implemented: true,
    icon: 'ClipboardPen',
  },
  {
    id: 'flatten-pdf',
    path: '/tools/flatten-pdf',
    title: 'Flatten PDF',
    description: 'Flatten fillable forms or rasterize pages to images — client-side.',
    implemented: true,
    icon: 'Layers',
  },
  { id: 'unlock-pdf', path: '/tools/unlock-pdf', title: 'Unlock PDF', description: 'Remove password via your API (qpdf / Ghostscript when configured).', implemented: true, icon: 'LockOpen' },
  {
    id: 'encrypt-pdf',
    path: '/tools/encrypt-pdf',
    title: 'Encrypt PDF',
    description: 'Password-protect with AES-256 (qpdf on the server).',
    implemented: true,
    icon: 'Lock',
  },
  {
    id: 'add-watermark',
    path: '/tools/add-watermark',
    title: 'Add Watermark',
    description: 'Text or image watermark, page ranges, preview, then download.',
    implemented: true,
    icon: 'Droplets',
  },
  {
    id: 'pdf-to-word',
    path: '/tools/pdf-to-word',
    title: 'PDF to Word',
    description: 'Draft .docx in your browser — PDF is not uploaded for conversion (use OCR PDF for scans first).',
    implemented: true,
    icon: 'FileType2',
  },
  {
    id: 'word-to-pdf',
    path: '/tools/word-to-pdf',
    title: 'Word to PDF',
    description: 'Draft PDF in your browser — .docx is not uploaded for conversion.',
    implemented: true,
    icon: 'FileText',
  },
  {
    id: 'gst-invoice',
    path: '/tools/gst-invoice',
    title: 'GST invoice PDF',
    description: 'Supplier, buyer, HSN lines — download a tax invoice PDF in the browser.',
    implemented: true,
    icon: 'Receipt',
  },
  {
    id: 'remove-pages',
    path: '/tools/remove-pages',
    title: 'Remove pages',
    description: 'Delete pages in the grid and download — same engine as Organize PDF (browser-only).',
    implemented: true,
    icon: 'Trash2',
  },
  {
    id: 'extract-pages',
    path: '/tools/extract-pages',
    title: 'Extract pages',
    description: 'Extract ranges or every page — same engine as Split PDF (browser-only).',
    implemented: true,
    icon: 'FileDown',
  },
  {
    id: 'repair-pdf',
    path: '/tools/repair-pdf',
    title: 'Repair PDF',
    description:
      'Recover many damaged PDFs — rewrites through qpdf on your API (optional password for encrypted files).',
    implemented: true,
    icon: 'Wrench',
  },
  {
    id: 'powerpoint-to-pdf',
    path: '/tools/powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Convert .pptx to PDF via your API (LibreOffice when SOFFICE_PATH is set).',
    implemented: true,
    icon: 'Presentation',
  },
  {
    id: 'excel-to-pdf',
    path: '/tools/excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert .xlsx to PDF via your API (LibreOffice when SOFFICE_PATH is set).',
    implemented: true,
    icon: 'Table2',
  },
  {
    id: 'html-to-pdf',
    path: '/tools/html-to-pdf',
    title: 'HTML to PDF',
    description: 'Convert a saved .html file to PDF via LibreOffice on your API.',
    implemented: true,
    icon: 'FileCode',
  },
  {
    id: 'pdf-to-powerpoint',
    path: '/tools/pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    description: 'Export .pptx from PDF via LibreOffice on your API (best-effort).',
    implemented: true,
    icon: 'Presentation',
  },
  {
    id: 'pdf-to-excel',
    path: '/tools/pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Export .xlsx from PDF via LibreOffice on your API (tables may need cleanup).',
    implemented: true,
    icon: 'Table2',
  },
  {
    id: 'pdf-to-pdfa',
    path: '/tools/pdf-to-pdfa',
    title: 'PDF to PDF/A',
    description: 'Long-term archival PDF/A — requires specialized validators and converters we will add behind your API.',
    implemented: true,
    icon: 'BadgeCheck',
  },
  {
    id: 'rotate-pdf',
    path: '/tools/rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate thumbnails then download — same engine as Organize PDF (browser-only).',
    implemented: true,
    icon: 'RotateCw',
  },
  {
    id: 'crop-pdf',
    path: '/tools/crop-pdf',
    title: 'Crop PDF',
    description: 'Trim the viewing area with a uniform crop on every page — in your browser (crop box).',
    implemented: true,
    icon: 'Crop',
  },
  {
    id: 'redact-pdf',
    path: '/tools/redact-pdf',
    title: 'Redact PDF',
    description: 'Black out a rectangular region on every page (browser). Hidden text may still exist — not legal-grade redaction.',
    implemented: true,
    icon: 'EyeOff',
  },
  {
    id: 'compare-pdf',
    path: '/tools/compare-pdf',
    title: 'Compare PDF',
    description: 'Compare selectable text between two PDFs line-by-line (run OCR on scans first).',
    implemented: true,
    icon: 'GitCompare',
  },
  {
    id: 'translate-pdf',
    path: '/tools/translate-pdf',
    title: 'Translate PDF',
    description: 'Extract text in-browser, translate with an on-device model (Transformers.js), download a simple text PDF.',
    implemented: true,
    icon: 'Languages',
  },
]
