/** Toolkit cards + paths. Each tool: src/features/<id>/ */
export const TOOL_REGISTRY = [
  { id: 'edit-pdf', path: '/tools/edit-pdf', title: 'Edit PDF', description: 'Change text, annotate, highlight, draw.', implemented: true, icon: 'FileEdit' },
  {
    id: 'ocr-pdf',
    path: '/tools/ocr-pdf',
    title: 'OCR PDF',
    description: 'Make scans searchable — needs your API (ocrmypdf + Tesseract on the server).',
    implemented: true,
    icon: 'ScanText',
  },
  {
    id: 'merge-pdf',
    path: '/tools/merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDFs into one file.',
    implemented: true,
    icon: 'GitMerge',
  },
  {
    id: 'split-pdf',
    path: '/tools/split-pdf',
    title: 'Split PDF',
    description: 'Split by page ranges or extract every page.',
    implemented: true,
    icon: 'Scissors',
  },
  {
    id: 'organize-pdf',
    path: '/tools/organize-pdf',
    title: 'Organize Pages',
    description: 'Reorder, rotate, or delete pages, then download.',
    implemented: true,
    icon: 'LayoutGrid',
  },
  {
    id: 'add-page-numbers',
    path: '/tools/add-page-numbers',
    title: 'Add page numbers',
    description: 'Stamp page numbers with placement, ranges, and formats — in your browser.',
    implemented: true,
    icon: 'Hash',
  },
  {
    id: 'compress-pdf',
    path: '/tools/compress-pdf',
    title: 'Compress PDF',
    description: 'Tries your API (qpdf / Ghostscript); falls back to in-browser pdf-lib when the API is missing.',
    implemented: true,
    icon: 'Minimize2',
  },
  { id: 'pdf-to-jpg', path: '/tools/pdf-to-jpg', title: 'PDF to JPG', description: 'Export pages as JPEG. ZIP or single files.', implemented: true, icon: 'ImageDown' },
  { id: 'jpg-to-pdf', path: '/tools/jpg-to-pdf', title: 'JPG to PDF', description: 'Combine images. Drag to reorder.', implemented: true, icon: 'Images' },
  {
    id: 'scan-to-pdf',
    path: '/tools/scan-to-pdf',
    title: 'Scan to PDF',
    description: 'Camera or photos: trim, enhance, multi-page PDF.',
    implemented: true,
    icon: 'ScanLine',
  },
  {
    id: 'sign-pdf',
    path: '/tools/sign-pdf',
    title: 'Sign PDF',
    description: 'Sign any page, duplicate or copy/paste placements, then download.',
    implemented: true,
    icon: 'PenLine',
  },
  { id: 'unlock-pdf', path: '/tools/unlock-pdf', title: 'Unlock PDF', description: 'Remove password via your API (qpdf / Ghostscript when configured).', implemented: true, icon: 'LockOpen' },
  {
    id: 'encrypt-pdf',
    path: '/tools/encrypt-pdf',
    title: 'Encrypt PDF',
    description: 'Password-protect with AES-256 (qpdf on the server).',
    implemented: true,
    icon: 'Lock',
  },
  {
    id: 'add-watermark',
    path: '/tools/add-watermark',
    title: 'Add Watermark',
    description: 'Text or image watermark, page ranges, preview, then download.',
    implemented: true,
    icon: 'Droplets',
  },
  {
    id: 'pdf-to-word',
    path: '/tools/pdf-to-word',
    title: 'PDF to Word',
    description: 'Draft .docx in your browser — PDF is not uploaded for conversion (use OCR PDF for scans first).',
    implemented: true,
    icon: 'FileType2',
  },
  {
    id: 'word-to-pdf',
    path: '/tools/word-to-pdf',
    title: 'Word to PDF',
    description: 'Needs configured API (LibreOffice and/or Gotenberg) — full layout fidelity is not done in-browser.',
    implemented: true,
    icon: 'FileText',
  },
  {
    id: 'gst-invoice',
    path: '/tools/gst-invoice',
    title: 'GST invoice PDF',
    description: 'Supplier, buyer, HSN lines — download a tax invoice PDF in the browser.',
    implemented: true,
    icon: 'Receipt',
  },
]
